import { gql, useMutation } from "@apollo/client";
import Head from "next/head";

export default function Home() {
  const UPLOAD_IMAGE = gql`
    mutation singleUpload($file: Upload!) {
      singleUpload(file: $file) {
        url
      }
    }
  `;

  const [singleUpload] = useMutation(UPLOAD_IMAGE, {
    onCompleted: (data) => console.log(data),
  });

  const handleFileChange = async (e) => {
    const file = e.target.files[0];

    if (!file) return;
    await singleUpload({ variables: { file } });
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <h1>Upload file</h1>
        <input type="file" onChange={handleFileChange} />
      </div>
    </div>
  );
}
